# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49d488b588b7001fae3e384165d5b3657dc131e7c6bdc9b9a4bfe148bdef6aa45597bf007ee8b85a821291db51085cd77568291175de2362c9b903901d4ca6e

test:
  secret_key_base: df509b464da53f942aefc18a650719f9469627c82e32e71d2af91959e312d510eeda5df28be67d15fde8cd6352387aa6ad0df4c67da51bc5bbdff924922687dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
